import type { BinConfig, PlacedObject, PlacedStl, PlacedText } from "../shared/types.ts";

const GRIDZ_DEFINE_MAP: Record<BinConfig["gridzMode"], number> = {
  increments: 0,
  internal: 1,
  external: 2,
  "external-with-lip": 3,
};

const STYLE_TAB_NONE = 5;

function num(n: number): string {
  return Number.isFinite(n) ? n.toFixed(4).replace(/\.?0+$/, "") : "0";
}

function escapeScadString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function renderStl(o: PlacedStl, stlPath: string): string {
  const [x, y, z] = o.position;
  const [ax, ay, az] = o.anchorOffset ?? [0, 0, 0];
  const oversize = 1 + o.oversizePct / 100;
  const unitScale = o.unitScale ?? 1;
  // Reads inside-out: import raw STL → scale to mm → translate by mm anchor →
  // oversize → rotate → final world position. Matches the client preview.
  return [
    `// stl: ${o.filename}`,
    `translate([${num(x)}, ${num(y)}, ${num(z)}])`,
    `rotate([0, 0, ${num(o.rotationZ)}])`,
    `scale([${num(oversize)}, ${num(oversize)}, ${num(oversize)}])`,
    `translate([${num(ax)}, ${num(ay)}, ${num(az)}])`,
    `scale([${num(unitScale)}, ${num(unitScale)}, ${num(unitScale)}])`,
    `import("${escapeScadString(stlPath)}", convexity = 10);`,
  ].join("\n  ");
}

function renderText(o: PlacedText): string {
  const [x, y, z] = o.position;
  const font = o.font ?? "Liberation Sans:style=Bold";
  return [
    `// text: ${o.text.slice(0, 40)}`,
    `translate([${num(x)}, ${num(y)}, ${num(z)}])`,
    `rotate([0, 0, ${num(o.rotationZ)}])`,
    `linear_extrude(height = ${num(Math.max(0.01, o.depth))}, center = false)`,
    `text("${escapeScadString(o.text)}", size = ${num(o.size)}, font = "${escapeScadString(font)}", halign = "center", valign = "center", $fn = 32);`,
  ].join("\n  ");
}

export interface ScadBuildArgs {
  bin: BinConfig;
  objects: PlacedObject[];
  stlPathFor: (filename: string) => string;
  libraryPath: string;
}

export function buildScad({ bin, objects, stlPathFor, libraryPath }: ScadBuildArgs): string {
  const includes = [
    `include <${libraryPath}/src/core/standard.scad>`,
    `use <${libraryPath}/src/core/gridfinity-rebuilt-utility.scad>`,
    `use <${libraryPath}/src/core/gridfinity-rebuilt-holes.scad>`,
    `use <${libraryPath}/src/core/bin.scad>`,
    `use <${libraryPath}/src/core/cutouts.scad>`,
    `use <${libraryPath}/src/helpers/generic-helpers.scad>`,
    `use <${libraryPath}/src/helpers/grid.scad>`,
    `use <${libraryPath}/src/helpers/grid_element.scad>`,
  ].join("\n");

  const gridzDefine = GRIDZ_DEFINE_MAP[bin.gridzMode];
  const holeOpts = `bundle_hole_options(refined_holes=${!bin.magnetHoles && !bin.screwHoles}, magnet_holes=${bin.magnetHoles}, screw_holes=${bin.screwHoles}, crush_ribs=true, chamfer_holes=true, printable_hole_top=true)`;

  const visibleObjects = objects.filter((o) => o.kind !== "stl" || !(o as PlacedStl).hidden);
  const embossText = visibleObjects.filter((o): o is PlacedText => o.kind === "text" && o.mode === "emboss");
  const cavityObjects = visibleObjects.filter((o) => o.kind === "stl" || (o.kind === "text" && o.mode === "deboss"));

  const cavityBody = cavityObjects
    .map((o) => (o.kind === "stl" ? renderStl(o, stlPathFor(o.filename)) : renderText(o)))
    .join("\n  ");

  const embossBody = embossText.map((t) => renderText(t)).join("\n  ");

  const subdivisionBlock =
    bin.divx > 0 && bin.divy > 0
      ? `bin_subdivide(bin_obj, [${bin.divx}, ${bin.divy}]) {
    cut_compartment_auto(cgs(), ${bin.styleTab}, false, ${num(bin.scoop)});
  }`
      : "";

  return `// Auto-generated by gridfinity-tool
$fa = 4;
$fs = 0.25;

${includes}

bin_obj = new_bin(
  grid_size = [${bin.gridx}, ${bin.gridy}],
  height_mm = height(${bin.gridz}, ${gridzDefine}, false),
  fill_height = 0,
  include_lip = ${bin.includeLip},
  hole_options = ${holeOpts},
  only_corners = ${bin.onlyCorners},
  thumbscrew = false
);

union() {
  bin_render(bin_obj) {
    ${subdivisionBlock}
    ${cavityBody}
  }
  ${embossBody ? `// Embossed text (added on top of bin)\n  ${embossBody}` : ""}
}
`;
}
